
--CREATE A DATABASE FOR RETAIL_SALES_ANALYSIS

CREATE DATABASE Retail_Sales_Analysis;



--CREATE TABLE AS RETAIL_SALES
CREATE TABLE RETAIL_SALES
(
	transactions_id	INT PRIMARY KEY,
	sale_date DATE,
	sale_time TIME,
	customer_id	INT,
	gender VARCHAR(15),
	age	INT,
	category VARCHAR(15),
	quantity	INT,
	price_per_unit FLOAT,
	cogs FLOAT,
	total_sale FLOAT
);




--IMPORT THE DATA INTO DATABASE 

--EXPLORING THE DATA :--


--FETCHING ALL THE RECORDS FROM TABLE
SELECT * FROM RETAIL_SALES


--COUNT ALL THE RECORDS FROM TABLE FOR VALIDATING THE RECORDS IS CORRECTLY IMPORTED OR NOT 
SELECT COUNT(*)
FROM RETAIL_SALES


--WHAT ARE THE PRODUCTS CATEGORY WE HAVE 
SELECT DISTINCT CATEGORY 
FROM RETAIL_SALES


--CHECKING THE MISSING RECORDS IN THE DATASET 
SELECT * 
FROM RETAIL_SALES
WHERE TRANSACTIONS_ID IS NULL 
   OR SALE_DATE IS NULL 
   OR SALE_TIME IS NULL 
   OR CUSTOMER_ID IS NULL
   OR GENDER IS NULL
   OR AGE IS NULL	
   OR CATEGORY IS NULL
   OR QUANTITY IS NULL
   OR PRICE_PER_UNIT IS NULL
   OR COGS IS NULL
   OR TOTAL_SALE IS NULL


--CHECKING THE DUPLICATE RECORDS
SELECT TRANSACTIONS_ID,COUNT(TRANSACTIONS_ID) AS COUNT_TRANSACTIONS_ID
FROM RETAIL_SALES
GROUP BY TRANSACTIONS_ID
HAVING COUNT(TRANSACTIONS_ID) > 1




--DATA CLEANING :--

--REMOVING THE MISSING RECORDS AND DUPLICATE RECORDS FROM THE TABLE


--DELETING THE MISSING RECORDS FROM THE TABLE
DELETE FROM RETAIL_SALES
WHERE TRANSACTIONS_ID IS NULL 
   OR SALE_DATE IS NULL 
   OR SALE_TIME IS NULL 
   OR CUSTOMER_ID IS NULL
   OR GENDER IS NULL
   OR AGE IS NULL	
   OR CATEGORY IS NULL
   OR QUANTITY IS NULL
   OR PRICE_PER_UNIT IS NULL
   OR COGS IS NULL
   OR TOTAL_SALE IS NULL


--DELECTING THE DUPLICATE RECORDS FROM THE TABLE
DELETE FROM RETAIL_SALES
WHERE TRANSACTIONS_ID IN (
	SELECT TRANSACTIONS_ID
	FROM RETAIL_SALES
	GROUP BY TRANSACTIONS_ID
	HAVING COUNT(TRANSACTIONS_ID) > 1
	)	




--DATA ANALYSIS & BUSINESS KEY PROBLEMS & ANSWERS:--


--1.WRITE A SQL QUERY TO RETRIEVE ALL DATA FOR SALES MADE ON '2022-11-05'
SELECT * FROM RETAIL_SALES
WHERE SALE_DATE = '2022-11-05'




--2. WRITE A SQL QUERY TO RETRIVE ALL TRANSACTION WHERE THE CATEGORY IS 'Clothing' AND THE QUANTITY SOLD IS MORE THAN 3 IN THE MONTH OF NOV-2022.
SELECT * FROM RETAIL_SALES
WHERE CATEGORY = 'Clothing' AND QUANTITY > 3 AND TO_CHAR(SALE_DATE ,'YYYY-MM') = '2022-11'




--3.WRITE A SQL QUERY TO CALCULATE THE TOTAL SALES FOR EACH CATEGORY.
SELECT CATEGORY,SUM(TOTAL_SALE) AS TOTAL_SALE 
FROM RETAIL_SALES
GROUP BY 1





--4.WRITE A SQL QUERY TO RETRIEVE ALL DATA FROM  MOST YOUNGER CUSTOMER WE HAVE.
SELECT * 
FROM RETAIL_SALES
WHERE AGE IN (SELECT MIN(AGE)
             FROM RETAIL_SALES )




--5.WRITE A SQL QUERY TO GET HOW MANY MALE AND FEMALE CUSTOMER WE HAVE.
SELECT GENDER,COUNT(GENDER) AS CUST_GENDER
FROM RETAIL_SALES
GROUP BY GENDER




--6.WHAT IS THE MAXIMUM AGE OF THE FEMALE CUSTOMER.
SELECT MAX(AGE) age 
FROM RETAIL_SALES
WHERE GENDER = 'Female'




--7. FIND THE AVERAGE AGE OF THE CUSTOMER WHO PURCHASED FROM 'Beauty' CATEGORY.
SELECT ROUND(AVG(AGE)) AVERAGE_AGE 
FROM RETAIL_SALES
WHERE CATEGORY = 'Beauty'




--8.FIND ALL THE TRANSACTION WHERE TOTAL_SALE IS GREATER THAN 1000.
SELECT *  
FROM RETAIL_SALES
WHERE TOTAL_SALE >1000 




--9.FIND THE TOTAL NUMBER OF TRANSACTION  MADE BY EACH GENDER BY EACH CATEGORY.
SELECT CATEGORY,GENDER ,COUNT(*) NO_OF_TRANSACTION
FROM RETAIL_SALES
GROUP BY CATEGORY,GENDER
ORDER BY 1





--10.CALCULATE THE AVEGRAGE SALE IN EACH MONTH AND FIND OUT BEST SELLING MONTH IN EACH YEAR.
SELECT * 
FROM (	
		SELECT EXTRACT(YEAR FROM SALE_DATE) AS YEAR,
		       EXTRACT(MONTH FROM SALE_DATE) AS MONTH,
			   AVG(TOTAL_SALE) AS AVG_SALE,
			   RANK() OVER(PARTITION BY EXTRACT(YEAR FROM SALE_DATE) ORDER BY AVG(TOTAL_SALE) DESC ) RANK
		FROM RETAIL_SALES
		GROUP BY 1,2
	)
WHERE RANK = 1




--11.FIND OUT THE TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL_SALE.
SELECT CUSTOMER_ID , SUM(TOTAL_SALE) AS TOTAL_SALE
FROM RETAIL_SALES
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5




--12.FIND THE UNIQUE CUSTOMERS WHO PURCHASED ITEM FROM EACH CATEGORY.
SELECT CATEGORY,COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM RETAIL_SALES
GROUP BY 1




--13.CREATE A SHIFT AND NUMBER OF ORDERS (EXAMPLE MORNING <12 ,AFTERNOON BETWEEN 12 AND 17 ,EVENING > 17).
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
					)
SELECT TIME_SHIFT,COUNT(*) 
from HOURLY_SALE
GROUP BY TIME_SHIFT




--14.IN WHICH TIME SHIFT WE HAVE THE HIGHEST NUMBER OF ORDERS.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)
SELECT TIME_SHIFT,COUNT(*) AS NO_OF_ORDERS
from HOURLY_SALE
GROUP BY TIME_SHIFT
ORDER BY 2 DESC




--15.IN WHICH TIME SHIFT WE HAVE THE HIGHEST TOTAL_SALE.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)		
SELECT TIME_SHIFT,SUM(TOTAL_SALE) AS TOTAL_SALE
from HOURLY_SALE
GROUP BY TIME_SHIFT
ORDER BY 2 DESC




--16.IN WHICH TIME SHIFT WE HAVE THE HIGHEST NUMBER OF UNIQUE CUSTOMERS.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)
SELECT TIME_SHIFT,COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
from HOURLY_SALE
GROUP BY TIME_SHIFT
ORDER BY 2 DESC




--17.FIND THE TOTAL NUMBER OF TRANSACTION MADE BY EACH GENDER IN EACH TIME SHIFT.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)
SELECT TIME_SHIFT,GENDER,COUNT(*) AS NO_OF_TRANSACTION
from HOURLY_SALE	
GROUP BY TIME_SHIFT,GENDER




--18.FIND THE HIGHEST TOTAL_SALE MADE BY EACH GENDER IN EACH TIME SHIFT.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)
SELECT TIME_SHIFT,GENDER,MAX(TOTAL_SALE) AS HIGHEST_TOTAL_SALE
from HOURLY_SALE		
GROUP BY TIME_SHIFT,GENDER
ORDER BY 1,2




--19.FIND WHICH CATEGORY HAS THE HIGHEST NUMBER OF TRANSACTION IN EACH TIME SHIFT.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)
SELECT TIME_SHIFT,CATEGORY,COUNT(*) AS NO_OF_TRANSACTION
from HOURLY_SALE
GROUP BY TIME_SHIFT,CATEGORY
ORDER BY TIME_SHIFT,COUNT(*) DESC




--20.FIND WHICH CATEGORY LOVED BY EACH GENDER IN EACH TIME SHIFT.
WITH HOURLY_SALE AS (
						SELECT *,
								 CASE
									 WHEN EXTRACT(HOUR FROM SALE_TIME) < 12 THEN 'MORNING'
									 WHEN EXTRACT(HOUR FROM SALE_TIME) BETWEEN 12 AND 17 THEN 'AFTERNOON'
									 ELSE 'EVENING'
								 END AS TIME_SHIFT          
						FROM RETAIL_SALES
				
					)
SELECT TIME_SHIFT,GENDER,CATEGORY,COUNT(*) AS NO_OF_TRANSACTION
from HOURLY_SALE	
GROUP BY TIME_SHIFT,GENDER,CATEGORY
ORDER BY TIME_SHIFT,GENDER,COUNT(*) DESC	




--END OF PROJECT--



